[package]
name = "frostbit"
version = "0.1.0"
edition = "2021"

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[dev-dependencies]
loom = "0.7"
rstest = "0.24.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }
